language: python

python:
  - "3.6"
  - "nightly"

matrix:
  allow_failures:
    - python: "nightly"

install:
    - ./bootstrap.sh

script:
    - inv lint
    - inv test --cov

after_success:
    - codecov
