__title__ = 'newio-requests'
__description__ = 'Newio + Requests: Async HTTP for Humans.'
__url__ = 'https://github.com/guyskk/newio-requests'
__version__ = '0.5.0'
__author__ = 'guyskk'
__author_email__ = 'guyskk@qq.com'
__license__ = 'MIT'
